# Generated by Django 2.1.7 on 2020-08-07 18:09

import UploadFiles.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='subcategory',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='year_published',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1984), UploadFiles.models.max_value_current_year]),
        ),
    ]
