# Generated by Django 2.1.7 on 2020-08-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0004_auto_20200807_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
