# Generated by Django 2.1.7 on 2020-08-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0006_auto_20200808_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
