# Generated by Django 2.1.7 on 2020-08-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0009_auto_20200808_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='thumbnail',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
