# Generated by Django 2.1.7 on 2020-08-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0010_auto_20200808_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
