# Generated by Django 2.1.7 on 2020-09-02 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0016_document_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='slug',
        ),
    ]
