# Generated by Django 2.1.7 on 2020-11-17 06:19

import UploadFiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0024_auto_20201117_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='eBookFile',
        ),
        migrations.AddField(
            model_name='document',
            name='eBookFile',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d', validators=[UploadFiles.validators.validate_file_extension]),
        ),
        migrations.DeleteModel(
            name='DocumentFile',
        ),
    ]
