# Generated by Django 2.1.7 on 2020-11-19 11:45

import UploadFiles.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0025_auto_20201117_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eBookFiles', models.FileField(upload_to='documents/%Y/%m/%d', validators=[UploadFiles.validators.validate_file_extension])),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='eBookFile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='doc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='UploadFiles.Document'),
        ),
    ]
