# Generated by Django 2.1.7 on 2020-11-19 11:55

import UploadFiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0027_auto_20201119_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eBookFile', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d', validators=[UploadFiles.validators.validate_file_extension])),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='eBookFile',
        ),
        migrations.AddField(
            model_name='document',
            name='eBookFiles',
            field=models.ManyToManyField(to='UploadFiles.DocumentFile'),
        ),
    ]
