# Generated by Django 2.1.7 on 2020-11-19 11:58

import UploadFiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0028_auto_20201119_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='eBookFiles',
        ),
        migrations.AddField(
            model_name='document',
            name='eBookFile',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d', validators=[UploadFiles.validators.validate_file_extension]),
        ),
        migrations.DeleteModel(
            name='DocumentFile',
        ),
    ]
