# Generated by Django 2.1.7 on 2020-11-25 06:22

import UploadFiles.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0029_auto_20201119_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eBookFile', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d', validators=[UploadFiles.validators.validate_file_extension])),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='eBookFile',
        ),
        migrations.AddField(
            model_name='documentfile',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UploadFiles.Document'),
        ),
    ]
