# Generated by Django 2.1.7 on 2020-11-25 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0030_auto_20201125_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='UploadFiles.Document'),
        ),
    ]
